spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:nishant?@980}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    require-ssl: false

# Application specific properties
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForPayFlowApplicationThatIsVerySecure}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Logging configuration
logging:
  level:
    com.payflow: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/payflow.log

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.payflow: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    root: WARN
    com.payflow: INFO